package dns

import (
	"bytes"
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
	"time"

	"servika/internal/logx"
)

const (
	// ZoneDir is the directory containing generated BIND zone files.
	ZoneDir = "/var/named"
	// NamedConfInclude is the generated BIND zone include file.
	NamedConfInclude = "/etc/named/servika-zones.conf"
	// DNSSECKeyDir stores keys generated by the BIND DNSSEC policy.
	DNSSECKeyDir = "/var/named/dynamic"
)

// fqdn ensures target domain names for NS, MX, CNAME, SRV, and PTR records end with a dot.
// This prevents BIND from interpreting them as relative names and appending the zone name.
func fqdn(rtype, value string) string {
	t := strings.ToUpper(strings.TrimSpace(rtype))
	d := strings.TrimSpace(value)
	if t == "NS" || t == "MX" || t == "CNAME" || t == "SRV" || t == "PTR" {
		if !strings.HasSuffix(d, ".") {
			d = d + "."
		}
	}
	return d
}

func txtQuote(value string) string {
	data := []byte(value)
	if len(data) == 0 {
		return `""`
	}
	segments := make([]string, 0, (len(data)+254)/255)
	for len(data) > 0 {
		length := min(255, len(data))
		var escaped strings.Builder
		for _, b := range data[:length] {
			switch {
			case b == '\\' || b == '"':
				escaped.WriteByte('\\')
				escaped.WriteByte(b)
			case b < 32 || b == 127:
				fmt.Fprintf(&escaped, `\%03d`, b)
			default:
				escaped.WriteByte(b)
			}
		}
		segments = append(segments, `"`+escaped.String()+`"`)
		data = data[length:]
	}
	return strings.Join(segments, " ")
}

func rdata(recordType, value string) string {
	if strings.EqualFold(strings.TrimSpace(recordType), "TXT") {
		return txtQuote(value)
	}
	return fqdn(recordType, value)
}

var zoneTmpl = template.Must(template.New("z").Funcs(template.FuncMap{
	"rdata":   rdata,
	"soaHost": soaHost,
	"soaMail": soaMail,
}).Parse(`$TTL {{.SOA.TTL}}
@   IN  SOA {{soaHost .SOA.PrimaryNS}} {{soaMail .SOA.Hostmaster}} (
    {{.Serial}}  ; serial
    {{.SOA.Refresh}}  ; refresh
    {{.SOA.Retry}}  ; retry
    {{.SOA.Expire}}  ; expire
    {{.SOA.Minimum}}  ; minimum
)
{{range .Records}}{{.Name}}	{{.TTL}}	IN	{{.Type}}	{{if or (eq .Type "MX") (eq .Type "SRV")}}{{.Priority}} {{end}}{{rdata .Type .Value}}
{{end}}`))

func soaHost(primaryNS string) string {
	primaryNS = strings.TrimSpace(primaryNS)
	if primaryNS == "" {
		return "."
	}
	if !strings.HasSuffix(primaryNS, ".") {
		primaryNS += "."
	}
	return primaryNS
}

func soaMail(hostmaster string) string {
	hostmaster = strings.TrimSpace(hostmaster)
	if i := strings.Index(hostmaster, "@"); i >= 0 {
		hostmaster = hostmaster[:i] + "." + hostmaster[i+1:]
	}
	if hostmaster == "" {
		return "."
	}
	if !strings.HasSuffix(hostmaster, ".") {
		hostmaster += "."
	}
	return hostmaster
}

type zoneCtx struct {
	DomainName string
	Serial     string
	SOA        SOA
	Records    []Record
}

func readZoneSerial(path string) uint32 {
	// #nosec G304 -- path is a fixed system/config path, a server-internal temp/archive path, or built from a validated identifier; tenant file reads go through safeio (openat2), not this call.
	body, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	for line := range strings.SplitSeq(string(body), "\n") {
		if !strings.Contains(line, "; serial") {
			continue
		}
		for field := range strings.FieldsSeq(line) {
			serial, parseErr := strconv.ParseUint(field, 10, 32)
			if parseErr == nil {
				return uint32(serial)
			}
		}
	}
	return 0
}

func nextSerialAt(old uint32, now time.Time) uint32 {
	// #nosec G115 -- YYYYMMDD00 serial (~2.03e9) always fits in uint32 (max 4.29e9); no overflow.
	base := uint32(now.UTC().Year()*1000000 + int(now.UTC().Month())*10000 + now.UTC().Day()*100)
	if old >= base && old < ^uint32(0) {
		return old + 1
	}
	return base
}

func nextSerial(old uint32) uint32 {
	return nextSerialAt(old, time.Now())
}

// WriteZone renders and validates the BIND zone file for a domain.
func WriteZone(ctx context.Context, db *sql.DB, domainID int64) error {
	var domainName string
	if err := db.QueryRowContext(ctx, `SELECT domain_name FROM domains WHERE id=?`, domainID).Scan(&domainName); err != nil {
		return err
	}
	// The name is validated where a domain is created, but it is read back from
	// the row here and a row outlives the code that wrote it. It becomes the leaf
	// of the zone path below, and of the .bak and .tmp paths beside it, so a
	// separator or a ".." would place all three outside ZoneDir.
	if !zoneLeafName(domainName) {
		return fmt.Errorf("invalid domain name for a zone file: %q", domainName)
	}
	records, err := zoneRecords(ctx, db, domainID)
	if err != nil {
		return err
	}
	if len(records) == 0 {
		return nil
	}

	if err := os.MkdirAll(zoneDirectory, 0750); err != nil {
		return err
	}
	zonePath := filepath.Join(zoneDirectory, domainName+".zone")
	if err := replaceZoneFile(ctx, db, domainID, domainName, zonePath, records); err != nil {
		return err
	}
	// #nosec G204 G702 -- fixed binaries (chown/restorecon) with constant/internal args (no shell); no tenant input.
	_, _ = zoneCommand("chown", "named:named", zonePath).CombinedOutput()
	// #nosec G204 G702 -- fixed binary (restorecon) with internal zone path (no shell); no tenant input.
	_, _ = zoneCommand("restorecon", zonePath).CombinedOutput()

	if err := updateZoneIncludes(ctx, db); err != nil {
		return err
	}
	reloadNamed()
	return nil
}

// zoneRecords returns the enabled records the zone file must carry.
func zoneRecords(ctx context.Context, db *sql.DB, domainID int64) ([]Record, error) {
	rows, err := db.QueryContext(ctx,
		`SELECT id, domain_id, name, type, value, ttl, priority, enabled,
		   DATE_FORMAT(created_at,'%Y-%m-%d %H:%i') FROM dns_records
		 WHERE domain_id=? AND enabled=1 ORDER BY type, name`, domainID)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	records := make([]Record, 0)
	for rows.Next() {
		record, err := scan(rows)
		if err != nil {
			// A dropped row is a record that silently disappears from the zone this
			// function is about to serve, so the write fails instead. Leaving the
			// previous zone in place is the safe outcome; a short zone is not.
			return nil, err
		}
		records = append(records, record)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return records, nil
}

// replaceZoneFile renders the zone beside the current one, refuses it when
// named-checkzone does, and only then puts it in place.
func replaceZoneFile(ctx context.Context, db *sql.DB, domainID int64, domainName, zonePath string, records []Record) error {
	serial := strconv.FormatUint(uint64(nextSerial(readZoneSerial(zonePath))), 10)

	soa := LoadSOA(ctx, db, domainID, domainName)
	var buf bytes.Buffer
	if err := zoneTmpl.Execute(&buf, zoneCtx{DomainName: domainName, Serial: serial, SOA: soa, Records: records}); err != nil {
		return err
	}
	tmpPath := zonePath + ".tmp"
	// #nosec G306 -- root-owned system integration file (nginx/php-fpm/named/systemd config, script, or web content) that its daemon must read/execute; no secret stored here (secrets use 0600/0640).
	if err := os.WriteFile(tmpPath, buf.Bytes(), 0640); err != nil {
		return err
	}
	// #nosec G204 G702 -- fixed binary (named-checkzone) with separate args (no shell); domainName is validated before this point.
	if out, err := zoneCommand("named-checkzone", domainName, tmpPath).CombinedOutput(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("named-checkzone: %s: %w", strings.TrimSpace(string(out)), err)
	}
	// #nosec G304 -- path is a fixed system/config path, a server-internal temp/archive path, or built from a validated identifier; tenant file reads go through safeio (openat2), not this call.
	if previous, readErr := os.ReadFile(zonePath); readErr == nil {
		// #nosec G306 G703 -- root-owned system integration file (nginx/php-fpm/named/systemd config, script, or web content) that its daemon must read/execute; no secret stored here (secrets use 0600/0640).
		_ = os.WriteFile(zonePath+".bak", previous, 0640)
	}
	if err := os.Rename(tmpPath, zonePath); err != nil {
		_ = os.Remove(tmpPath)
		return err
	}
	return nil
}

// reloadNamed reloads BIND and validates the configuration before a restart fallback.
func reloadNamed() {
	if err := zoneCommand("rndc", "reload").Run(); err == nil {
		return
	}
	if err := zoneCommand("systemctl", "reload", "named").Run(); err == nil {
		return
	}
	if err := zoneCommand("named-checkconf").Run(); err != nil {
		logx.Warnf("dns reload: named-checkconf failed; named restart skipped: %v", err)
		return
	}
	_ = zoneCommand("systemctl", "restart", "named").Run()
}

func zoneIncludeStatement(domainName string, dnssec bool) string {
	statement := fmt.Sprintf(`zone "%s" { type master; file "%s/%s.zone"; allow-query { any; }; allow-transfer { none; };`,
		domainName, ZoneDir, domainName)
	if dnssec {
		statement += fmt.Sprintf(` dnssec-policy default; key-directory "%s"; inline-signing yes;`, DNSSECKeyDir)
	}
	return statement + " };\n"
}

func buildZoneIncludes(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `SELECT d.domain_name, COALESCE(d.dnssec_active,0) FROM domains d
	  WHERE EXISTS (SELECT 1 FROM dns_records r WHERE r.domain_id=d.id AND r.enabled=1)`)
	if err != nil {
		return "", err
	}
	defer func() { _ = rows.Close() }()
	var output strings.Builder
	output.WriteString("// Automatically generated by Servika\n")
	for rows.Next() {
		var domainName string
		var dnssec int
		if err := rows.Scan(&domainName, &dnssec); err != nil {
			return "", err
		}
		output.WriteString(zoneIncludeStatement(domainName, dnssec == 1))
	}
	if err := rows.Err(); err != nil {
		return "", err
	}
	return output.String(), nil
}

func updateZoneIncludes(ctx context.Context, db *sql.DB) error {
	content, err := buildZoneIncludes(ctx, db)
	if err != nil {
		return err
	}
	tmpPath := namedConfIncludePath + ".tmp"
	// #nosec G306 -- root-owned system integration file (nginx/php-fpm/named/systemd config, script, or web content) that its daemon must read/execute; no secret stored here (secrets use 0600/0640).
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return err
	}
	if output, checkErr := zoneCommand("named-checkconf", tmpPath).CombinedOutput(); checkErr != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("validate generated zone include: %s: %w", strings.TrimSpace(string(output)), checkErr)
	}
	if err := os.Rename(tmpPath, namedConfIncludePath); err != nil {
		_ = os.Remove(tmpPath)
		return err
	}
	_, _ = zoneCommand("restorecon", namedConfIncludePath).CombinedOutput()
	return nil
}

// HealZoneIncludes reapplies transfer restrictions and DNSSEC policy to every managed zone include.
func HealZoneIncludes(ctx context.Context, db *sql.DB) error {
	if err := updateZoneIncludes(ctx, db); err != nil {
		return err
	}
	reloadNamed()
	return nil
}

// DeleteZone removes a domain's BIND zone file and reloads the zone list.
// zoneLeafName reports whether a domain name may become the leaf of a path
// under ZoneDir. Both the write and the delete path build a file name from a
// value read back out of a row, and a row outlives the code that wrote it, so
// each asks this before it touches the filesystem.
func zoneLeafName(domainName string) bool {
	return domainName != "" &&
		!strings.ContainsAny(domainName, `/\`) &&
		!strings.Contains(domainName, "..")
}

func DeleteZone(ctx context.Context, db *sql.DB, domainName string) error {
	// The same gate WriteZone carries, on the path that REMOVES a file rather
	// than writing one. The caller reads the name out of a row, so a separator or
	// a ".." in that column would delete an arbitrary file whose name happens to
	// end in ".zone".
	if !zoneLeafName(domainName) {
		return fmt.Errorf("invalid domain name for a zone file: %q", domainName)
	}
	_ = os.Remove(filepath.Join(ZoneDir, domainName+".zone"))
	_ = updateZoneIncludes(ctx, db)
	reloadNamed()
	return nil
}
