// Package cron manages crontab entries for domain users.
package cron

import (
	"bufio"
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"time"

	"servika/internal/httpx"

	"github.com/go-chi/chi/v5"
)

// runTimeout bounds a manual cron run so a wedged command cannot hold the request.
const runTimeout = 120 * time.Second

// runOutputLimit is how much combined output a manual run returns; the tail is
// kept because a failing command's error is usually at the end.
const runOutputLimit = 8192

const (
	maxTasks         = 100
	maxCommandLength = 1024
	bannerLine       = "# servika cron: this file is managed by the panel; do not edit manually"
)

type Task struct {
	Idx     int    `json:"idx"`
	Minute  string `json:"minute"`
	Hour    string `json:"hour"`
	Day     string `json:"day"`
	Month   string `json:"month"`
	Week    string `json:"week"`
	Command string `json:"command"`
	Comment string `json:"comment,omitempty"`
}

type Handlers struct {
	DB *sql.DB
}

var (
	errDemo = errors.New("cron cannot be managed for a demo subscription")
	errBad  = errors.New("security: user without c_ prefix rejected")
)

func (h *Handlers) lookup(r *http.Request) (string, error) {
	id, _ := strconv.ParseInt(chi.URLParam(r, "id"), 10, 64)
	var systemUser string
	var isDemo int
	err := h.DB.QueryRowContext(r.Context(),
		`SELECT system_user, is_demo FROM domains WHERE id=?`, id).
		Scan(&systemUser, &isDemo)
	if errors.Is(err, sql.ErrNoRows) {
		return "", os.ErrNotExist
	}
	if err != nil {
		return "", err
	}
	if isDemo == 1 {
		return "", errDemo
	}
	if !strings.HasPrefix(systemUser, "c_") {
		return "", errBad
	}
	return systemUser, nil
}

// cronPath returns the domain user's crontab path.
func cronPath(systemUser string) string {
	return "/var/spool/cron/" + systemUser
}

func read(systemUser string) ([]Task, error) {
	p := cronPath(systemUser)
	// #nosec G703 G304 -- path is built from a validated identifier (systemUser ^c_[A-Za-z0-9_]+$ / validated domainName), a fixed system path, or a server-internal temp path; tenant file-manager paths use safeio (openat2) instead.
	f, err := os.Open(p)
	if err != nil {
		if os.IsNotExist(err) {
			return []Task{}, nil
		}
		return nil, err
	}
	defer func() { _ = f.Close() }()
	out := make([]Task, 0)
	sc := bufio.NewScanner(f)
	var lastComment string
	idx := 0
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			lastComment = ""
			continue
		}
		if c, found := strings.CutPrefix(line, "#"); found {
			c = strings.TrimSpace(c)
			// Skip the banner generated by this package.
			if !strings.HasPrefix(c, "servika") {
				lastComment = c
			}
			continue
		}
		// Parse five schedule fields followed by the command.
		fields := strings.Fields(line)
		if len(fields) < 6 {
			continue
		}
		out = append(out, Task{
			Idx:    idx,
			Minute: fields[0], Hour: fields[1], Day: fields[2],
			Month: fields[3], Week: fields[4],
			Command: strings.Join(fields[5:], " "),
			Comment: lastComment,
		})
		idx++
		lastComment = ""
	}
	return out, sc.Err()
}

func write(systemUser string, list []Task) error {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "%s\n", bannerLine)
	fmt.Fprintf(&buf, "# last update: %s\n\n", systemUser)
	for _, task := range list {
		if task.Comment != "" {
			fmt.Fprintf(&buf, "# %s\n", strings.ReplaceAll(task.Comment, "\n", " "))
		}
		fmt.Fprintf(&buf, "%s %s %s %s %s %s\n",
			task.Minute, task.Hour, task.Day, task.Month, task.Week, task.Command)
	}
	p := cronPath(systemUser)
	tmp := p + ".tmp"
	// #nosec G703 -- path is built from a validated identifier (systemUser ^c_[A-Za-z0-9_]+$ / validated domainName), a fixed system path, or a server-internal temp path; tenant file-manager paths use safeio (openat2) instead.
	if err := os.WriteFile(tmp, buf.Bytes(), 0600); err != nil {
		return err
	}
	// #nosec G703 -- path is built from a validated identifier (systemUser ^c_[A-Za-z0-9_]+$ / validated domainName), a fixed system path, or a server-internal temp path; tenant file-manager paths use safeio (openat2) instead.
	if err := os.Rename(tmp, p); err != nil {
		return err
	}
	// #nosec G703 -- path is built from a validated identifier (systemUser ^c_[A-Za-z0-9_]+$ / validated domainName), a fixed system path, or a server-internal temp path; tenant file-manager paths use safeio (openat2) instead.
	_ = os.Chmod(p, 0600)
	// Set ownership to the domain user.
	// #nosec G204 G702 -- fixed binary with separate args (no shell); tenant input is validated before exec.
	if out, err := exec.Command("chown", systemUser+":"+systemUser, p).CombinedOutput(); err != nil {
		return fmt.Errorf("chown: %s: %w", strings.TrimSpace(string(out)), err)
	}
	// SELinux context — system_cron_spool_t
	// #nosec G204 G702 -- fixed binary with separate args (no shell); tenant input is validated before exec.
	_, _ = exec.Command("restorecon", p).CombinedOutput()
	return nil
}

func validate(task Task) error {
	if task.Minute == "" || task.Hour == "" || task.Day == "" || task.Month == "" || task.Week == "" {
		return fmt.Errorf("all schedule fields are required")
	}
	if task.Command == "" {
		return fmt.Errorf("command cannot be empty")
	}
	if len(task.Command) > maxCommandLength {
		return fmt.Errorf("command is too long (max %d)", maxCommandLength)
	}
	for _, field := range []string{task.Minute, task.Hour, task.Day, task.Month, task.Week} {
		if strings.ContainsAny(field, ";|&`\n") {
			return fmt.Errorf("invalid character in schedule fields")
		}
	}
	if strings.ContainsAny(task.Command, "\n\r") {
		return fmt.Errorf("command cannot contain line breaks")
	}
	return nil
}

func statusFromErr(err error) int {
	switch err {
	case os.ErrNotExist:
		return http.StatusNotFound
	case errDemo:
		return http.StatusForbidden
	case errBad:
		return http.StatusBadRequest
	}
	return http.StatusInternalServerError
}

func (h *Handlers) List(w http.ResponseWriter, r *http.Request) {
	systemUser, err := h.lookup(r)
	if err != nil {
		httpx.WriteError(w, statusFromErr(err), "operation failed")
		return
	}
	list, err := read(systemUser)
	if err != nil {
		httpx.WriteError(w, http.StatusInternalServerError, "operation failed")
		return
	}
	httpx.WriteJSON(w, http.StatusOK, map[string]any{
		"system_user": systemUser,
		"total":       len(list),
		"tasks":       list,
	})
}

func (h *Handlers) Create(w http.ResponseWriter, r *http.Request) {
	systemUser, err := h.lookup(r)
	if err != nil {
		httpx.WriteError(w, statusFromErr(err), "operation failed")
		return
	}
	var task Task
	if err := json.NewDecoder(r.Body).Decode(&task); err != nil {
		httpx.WriteError(w, http.StatusBadRequest, "invalid request body")
		return
	}
	if err := validate(task); err != nil {
		httpx.WriteError(w, http.StatusBadRequest, "invalid request")
		return
	}
	list, err := read(systemUser)
	if err != nil {
		httpx.WriteError(w, http.StatusInternalServerError, "operation failed")
		return
	}
	if len(list) >= maxTasks {
		httpx.WriteError(w, http.StatusBadRequest, fmt.Sprintf("at most %d tasks are allowed", maxTasks))
		return
	}
	list = append(list, task)
	if err := write(systemUser, list); err != nil {
		httpx.WriteError(w, http.StatusInternalServerError, "operation failed")
		return
	}
	httpx.WriteJSON(w, http.StatusCreated, map[string]any{"ok": true, "idx": len(list) - 1})
}

func (h *Handlers) Delete(w http.ResponseWriter, r *http.Request) {
	systemUser, err := h.lookup(r)
	if err != nil {
		httpx.WriteError(w, statusFromErr(err), "operation failed")
		return
	}
	idx, _ := strconv.Atoi(chi.URLParam(r, "idx"))
	list, err := read(systemUser)
	if err != nil {
		httpx.WriteError(w, http.StatusInternalServerError, "operation failed")
		return
	}
	if idx < 0 || idx >= len(list) {
		httpx.WriteError(w, http.StatusNotFound, "index out of range")
		return
	}
	deleted := list[idx]
	list = append(list[:idx], list[idx+1:]...)
	if err := write(systemUser, list); err != nil {
		httpx.WriteError(w, http.StatusInternalServerError, "operation failed")
		return
	}
	httpx.WriteJSON(w, http.StatusOK, map[string]any{"ok": true, "deleted": deleted})
}

// Run triggers one cron task by hand (a test/verification run). The task's command
// runs as the tenant user, with a clean environment carrying no panel secrets, a
// 120-second timeout, and the tail of the combined output returned.
//
// Security: the command is read from the tenant's OWN crontab (they wrote it) and
// was already going to run under their own identity, so this only brings the time
// forward. runuser drops to the tenant; no privilege is added. lookup enforces the
// demo and scope checks.
func (h *Handlers) Run(w http.ResponseWriter, r *http.Request) {
	systemUser, err := h.lookup(r)
	if err != nil {
		httpx.WriteError(w, statusFromErr(err), "operation failed")
		return
	}
	idx, _ := strconv.Atoi(chi.URLParam(r, "idx"))
	list, err := read(systemUser)
	if err != nil {
		httpx.WriteError(w, http.StatusInternalServerError, "operation failed")
		return
	}
	if idx < 0 || idx >= len(list) {
		httpx.WriteError(w, http.StatusNotFound, "index out of range")
		return
	}
	command := list[idx].Command

	ctx, cancel := context.WithTimeout(r.Context(), runTimeout)
	defer cancel()
	// #nosec G204 G702 -- runuser drops to the validated tenant account (systemUser ^c_[A-Za-z0-9_]+$); the command is the tenant's own crontab entry, already destined to run under this identity by cron, so no new capability is granted and this only brings the run forward.
	cmd := exec.CommandContext(ctx, "runuser", "-u", systemUser, "--", "/bin/sh", "-c", command)
	cmd.Env = []string{
		"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
		"HOME=/home/" + systemUser,
	}
	out, runErr := cmd.CombinedOutput()
	output := string(out)
	if len(output) > runOutputLimit {
		output = "...(truncated)\n" + output[len(output)-runOutputLimit:]
	}
	resp := map[string]any{"ok": runErr == nil, "output": output, "command": command}
	if runErr != nil {
		if ctx.Err() == context.DeadlineExceeded {
			resp["error"] = "timed out (120s); the task may still be running in the background"
		} else {
			resp["error"] = runErr.Error()
		}
	}
	httpx.WriteJSON(w, http.StatusOK, resp)
}
