package panelport

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// helperUnit is the transient unit the detached change runs under.
const helperUnit = "servika-panel-port-change"

// The helper is a shell script rather than a second Go binary for one reason:
// it has to survive the restart of the only Go binary on this server. A second
// binary shipped beside servika-server would be replaced by the same update
// that replaces servika-server, and an update landing mid-change would leave
// the helper and the panel disagreeing about what they were doing.
//
// It carries NO database credentials. Its verdict goes into a file, which the
// panel reads on its way back up. Putting the DSN in a root script for the sake
// of one row would be a worse trade than the extra step.
//
// It does not use "set -e": a failure in the rollback must not stop the rest of
// the rollback, and the whole point of this script is what it does when things
// have already gone wrong.
const helperTemplate = `#!/usr/bin/env bash
# Generated by Servika for one panel port change. Regenerated on each change.
set -uo pipefail

OUTCOME=%s
PROBE_HOST=%s
NEW_PORT=%d
OLD_PORT=%d
DEADLINE=%d

write_outcome() {
  # $1 state, $2 error text
  printf '%%s' "$(cat <<JSON
{"history_id":%d,"kind":"backend","old_port":${OLD_PORT},"new_port":${NEW_PORT},"state":"$1","error":"$2","finished_utc":"$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)"}
JSON
)" > "$OUTCOME"
  chmod 600 "$OUTCOME" 2>/dev/null || true
}

wait_for_port() {
  # $1 port. Returns 0 as soon as something accepts a connection.
  local waited=0
  while [ "$waited" -lt "$DEADLINE" ]; do
    if timeout 3 bash -c "exec 3<>/dev/tcp/${PROBE_HOST}/$1" 2>/dev/null; then
      return 0
    fi
    sleep 2
    waited=$((waited + 2))
  done
  return 1
}

systemctl restart servika.service
systemctl reload nginx 2>/dev/null

if wait_for_port "$NEW_PORT"; then
  write_outcome succeeded ""
  exit 0
fi

# Nothing came up on the new port. Put every file back, restart, and check that
# the old port really returned: "the change failed" and "the change failed and
# the panel is gone" need completely different things from an operator.
%s

systemctl restart servika.service
systemctl reload nginx 2>/dev/null

if wait_for_port "$OLD_PORT"; then
  write_outcome rolled_back "the panel did not answer on port ${NEW_PORT}"
else
  write_outcome rollback_failed "the panel answers on neither port ${NEW_PORT} nor port ${OLD_PORT}"
fi
`

// writeHelper renders the helper for one change.
//
// Every value interpolated here is a validated port, a fixed path, or a path
// this package generated, and the restore lines are built from the change set
// rather than from anything a request carried.
func writeHelper(changes []changeSet, current Ports, newPort int, historyID int64) error {
	probeHost := strings.Trim(current.BackendHost, "[]")
	if probeHost == "" || probeHost == "0.0.0.0" || probeHost == "::" {
		probeHost = "127.0.0.1"
	}
	if !plainHost(probeHost) {
		return fmt.Errorf("refusing to probe %q", probeHost)
	}

	var restore strings.Builder
	for _, change := range changes {
		if change.Backup == "" {
			// The file did not exist before, so putting it back means removing
			// it. That case is unreachable for the two files a backend change
			// touches; it is handled so a later addition cannot skip it.
			fmt.Fprintf(&restore, "rm -f %s\n", shellQuote(change.Path))
			continue
		}
		if !plainPath(change.Path) || !plainPath(change.Backup) {
			return fmt.Errorf("refusing to write a restore line for %q", change.Path)
		}
		fmt.Fprintf(&restore, "cp -p %s %s\n", shellQuote(change.Backup), shellQuote(change.Path))
	}

	body := fmt.Sprintf(helperTemplate,
		shellQuote(outcomePath()), shellQuote(probeHost),
		newPort, current.Backend, int(verifyDeadline.Seconds()),
		historyID, restore.String())

	// #nosec G306 -- a root-owned script systemd executes; it carries no
	// secret and every interpolated value is validated above.
	return os.WriteFile(helperPath(), []byte(body), 0o700)
}

// plainHost accepts only a literal address or a hostname made of characters
// that carry no meaning to a shell.
func plainHost(value string) bool {
	if value == "" || len(value) > 253 {
		return false
	}
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9',
			r == '.', r == '-', r == ':':
		default:
			return false
		}
	}
	return true
}

// plainPath accepts only an absolute path made of ordinary characters. The
// paths come from this package's own constants and from backupOne, so nothing
// can currently fail it; the check is what stops a later addition from turning
// a path into another shell word.
func plainPath(value string) bool {
	if !strings.HasPrefix(value, "/") || len(value) > 512 {
		return false
	}
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9',
			r == '/', r == '.', r == '-', r == '_':
		default:
			return false
		}
	}
	return !strings.Contains(value, "..")
}

// shellQuote wraps a value in single quotes. Combined with plainPath and
// plainHost it is belt and braces, which is the right amount for a string that
// becomes a line in a root script.
func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

// MarshalOutcome is used by tests to build the file the helper writes.
func MarshalOutcome(outcome Outcome) string {
	raw, _ := json.Marshal(outcome)
	return string(raw)
}

// RenderHelperForTest renders the helper against the paths currently
// configured, so the generated script can be exercised outside the panel.
func RenderHelperForTest() error {
	return writeHelper(
		[]changeSet{
			{Path: envPath(), Backup: envPath() + ".bak"},
			{Path: panelVhostPath(), Backup: panelVhostPath() + ".bak"},
		},
		Ports{Backend: 8080, BackendHost: "127.0.0.1", External: 8443},
		9090, 42)
}
