package provisioner

import (
	"database/sql/driver"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// HealSSLVhost443OnStartup repairs an SSL-enabled domain whose vhost lost its 443
// block or whose certificate files are gone, and leaves a healthy one alone. These
// tests run it against temporary directories with every host effect replaced.

const (
	sslDomainListQuery = "WHERE ssl_enabled=1"
	addonLookupQuery   = "parent_domain_id, COALESCE(web_root"
	certRepointQuery   = "UPDATE domains SET cert_path"
)

type sslHealFixture struct {
	certRoot string
	capture  *renderCapture
	commands *commandRecorder
}

// withSSLHeal points the heal at temporary directories, hands no file to root,
// answers no DNS, stands in for openssl by writing the files it would have
// written, and records renders instead of reloading nginx.
func withSSLHeal(t *testing.T) *sslHealFixture {
	t.Helper()
	withRootlessCertificates(t)
	setForTest(t, &nginxConfDir, t.TempDir())
	stubResolver(t, func(string) ([]string, error) { return nil, errors.New("no resolver in tests") })
	return &sslHealFixture{
		certRoot: certRoot(t),
		capture:  withRenderCapture(t),
		commands: withCommandScript(t, writeOpenSSLOutputs),
	}
}

// writeOpenSSLOutputs answers an openssl invocation by writing the key and the
// certificate it names, so the steps that follow find the files a real run
// leaves behind. Every other command succeeds silently.
func writeOpenSSLOutputs(argv []string) (string, int) {
	if len(argv) == 0 || argv[0] != "openssl" {
		return "", 0
	}
	for i, arg := range argv[:len(argv)-1] {
		if arg == "-keyout" || arg == "-out" {
			if err := os.WriteFile(argv[i+1], []byte("generated by the test"), 0o600); err != nil {
				return err.Error(), 1
			}
		}
	}
	return "", 0
}

// sslScript answers the heal's domain list, the addon lookup and the four reads
// applyVhostForDomain makes for whichever domain is re-rendered.
func sslScript(domains [][]driver.Value) *sqlScript {
	script := vhostScript(domainDetails("example.com", "c_example_com", "", "", "", "php-fpm", "", 0, 0, "", nil))
	script.rows[sslDomainListQuery] = domains
	script.rows[addonLookupQuery] = [][]driver.Value{}
	return script
}

// sslRow is one SSL-enabled domain in SELECT order.
func sslRow(id driver.Value, domain, user, cert, key string) []driver.Value {
	return []driver.Value{id, domain, user, "8.3", cert, key}
}

func sslVhost(t *testing.T, user, body string) {
	t.Helper()
	writeFixture(t, filepath.Join(nginxConfDir, "dom_"+user+".conf"), body)
}

// repoints returns the arguments of every certificate path update, in order.
func repoints(script *sqlScript) [][]driver.Value {
	script.mu.Lock()
	defer script.mu.Unlock()
	var out [][]driver.Value
	for _, exec := range script.execs {
		if strings.Contains(exec.query, certRepointQuery) {
			out = append(out, exec.args)
		}
	}
	return out
}

const (
	vhostWith443    = "server {\n    listen 443 ssl;\n}\n"
	vhostWithout443 = "server {\n    listen 80;\n}\n"
)

func TestAHealthySSLDomainIsLeftAlone(t *testing.T) {
	f := withSSLHeal(t)
	cert, key := writeSANCertificate(t, "example.com")
	sslVhost(t, "c_example_com", vhostWith443)
	script := sslScript([][]driver.Value{sslRow(int64(1), "example.com", "c_example_com", cert, key)})
	withScript(t, script)

	HealSSLVhost443OnStartup()

	if len(f.capture.opts) != 0 || len(repoints(script)) != 0 {
		t.Errorf("a healthy domain was repaired: renders %d, repoints %v", len(f.capture.opts), repoints(script))
	}
}

func TestAMissing443BlockIsRerenderedWithTheStoredCertificate(t *testing.T) {
	f := withSSLHeal(t)
	cert, key := writeSANCertificate(t, "example.com")
	sslVhost(t, "c_example_com", vhostWithout443)
	script := sslScript([][]driver.Value{sslRow(int64(1), "example.com", "c_example_com", cert, key)})
	withScript(t, script)

	HealSSLVhost443OnStartup()

	if len(f.capture.opts) != 1 {
		t.Fatalf("renders = %d, want the vhost re-rendered once", len(f.capture.opts))
	}
	if len(repoints(script)) != 0 || f.commands.ran("openssl") {
		t.Errorf("a present certificate was replaced: repoints %v, openssl %v", repoints(script), f.commands.ran("openssl"))
	}
}

// An addon domain is judged by its own vhost file, which a healthy parent vhost
// does not stand in for.
func TestAnAddonDomainIsJudgedByItsOwnVhost(t *testing.T) {
	f := withSSLHeal(t)
	cert, key := writeSANCertificate(t, "addon.example")
	sslVhost(t, "c_example_com", vhostWith443)
	script := sslScript([][]driver.Value{sslRow(int64(1), "addon.example", "c_example_com", cert, key)})
	script.rows[addonLookupQuery] = [][]driver.Value{{int64(9), ""}}
	withScript(t, script)

	HealSSLVhost443OnStartup()

	if len(f.capture.opts) != 1 {
		t.Errorf("renders = %d, want the addon repaired although the parent vhost has 443", len(f.capture.opts))
	}
}

func TestADomainWithAnInvalidNameIsSkipped(t *testing.T) {
	f := withSSLHeal(t)
	script := sslScript([][]driver.Value{
		sslRow(int64(1), "bad name", "c_example_com", "", ""),
		sslRow(int64(2), "", "c_example_com", "", ""),
	})
	withScript(t, script)

	HealSSLVhost443OnStartup()

	if len(f.capture.opts) != 0 || f.commands.ran("openssl") {
		t.Errorf("an invalid name was repaired: renders %d, commands %q", len(f.capture.opts), f.commands.argvs())
	}
}

func TestAMissingCertificateIsReplacedWithASelfSignedOne(t *testing.T) {
	f := withSSLHeal(t)
	sslVhost(t, "c_example_com", vhostWith443)
	script := sslScript([][]driver.Value{sslRow(int64(1), "example.com", "c_example_com", "/gone.crt", "/gone.key")})
	withScript(t, script)

	HealSSLVhost443OnStartup()

	if !f.commands.ran("openssl", "req", "-x509") {
		t.Fatalf("no self-signed certificate was generated: %q", f.commands.argvs())
	}
	dir := filepath.Join(f.certRoot, "example.com")
	want := [][]driver.Value{{filepath.Join(dir, "example.com.crt"), filepath.Join(dir, "example.com.key"), int64(1)}}
	if got := repoints(script); !reflect.DeepEqual(got, want) {
		t.Errorf("repoints = %v, want %v", got, want)
	}
	if len(f.capture.opts) != 1 {
		t.Errorf("renders = %d, want the vhost re-rendered once", len(f.capture.opts))
	}
}

// A valid certificate already in the system directory is put back in place
// before anything new is generated.
func TestAnInstalledSystemCertificateIsReusedBeforeGeneratingOne(t *testing.T) {
	f := withSSLHeal(t)
	dir := filepath.Join(f.certRoot, "example.com")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	cert, key := writeSANCertificate(t, "example.com")
	for source, target := range map[string]string{cert: filepath.Join(dir, "example.com.crt"), key: filepath.Join(dir, "example.com.key")} {
		body, err := os.ReadFile(source)
		if err != nil {
			t.Fatal(err)
		}
		writeFixture(t, target, string(body))
	}
	sslVhost(t, "c_example_com", vhostWith443)
	script := sslScript([][]driver.Value{sslRow(int64(1), "example.com", "c_example_com", "/gone.crt", "/gone.key")})
	withScript(t, script)

	HealSSLVhost443OnStartup()

	if f.commands.ran("openssl") {
		t.Error("a certificate was generated although a valid one was installed")
	}
	want := [][]driver.Value{{filepath.Join(dir, "example.com.crt"), filepath.Join(dir, "example.com.key"), int64(1)}}
	if got := repoints(script); !reflect.DeepEqual(got, want) {
		t.Errorf("repoints = %v, want %v", got, want)
	}
	if len(f.capture.opts) != 1 {
		t.Errorf("renders = %d, want the vhost re-rendered once", len(f.capture.opts))
	}
}

// A repair that cannot put a certificate in place or record it is not rendered,
// because the render reads the certificate from the domain row.
func TestAnSSLRepairThatCannotCompleteIsNotRendered(t *testing.T) {
	cases := []struct {
		name    string
		prepare func(f *sslHealFixture, script *sqlScript)
	}{
		{"the self-signed certificate cannot be generated", func(f *sslHealFixture, _ *sqlScript) {
			f.commands.respond = func(argv []string) (string, int) {
				if argv[0] == "openssl" {
					return "unable to write private key", 1
				}
				return "", 0
			}
		}},
		{"the domain row cannot be repointed", func(_ *sslHealFixture, script *sqlScript) {
			script.fail[certRepointQuery] = errors.New(lostConnectionTo)
		}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			f := withSSLHeal(t)
			sslVhost(t, "c_example_com", vhostWith443)
			script := sslScript([][]driver.Value{sslRow(int64(1), "example.com", "c_example_com", "/gone.crt", "/gone.key")})
			tc.prepare(f, script)
			withScript(t, script)

			HealSSLVhost443OnStartup()

			if len(f.capture.opts) != 0 {
				t.Errorf("renders = %d, want none", len(f.capture.opts))
			}
		})
	}
}

func TestARenderFailureDoesNotStopTheNextSSLDomain(t *testing.T) {
	f := withSSLHeal(t)
	f.capture.err = errors.New("nginx rejected the configuration")
	cert, key := writeSANCertificate(t, "first.example", "second.example")
	sslVhost(t, "c_first", vhostWithout443)
	sslVhost(t, "c_second", vhostWithout443)
	script := sslScript([][]driver.Value{
		sslRow(int64(1), "first.example", "c_first", cert, key),
		sslRow(int64(2), "second.example", "c_second", cert, key),
	})
	withScript(t, script)

	HealSSLVhost443OnStartup()

	if len(f.capture.opts) != 2 {
		t.Errorf("renders = %d, want both domains attempted", len(f.capture.opts))
	}
}

// The domain list is repaired as far as it could be read: a failed query repairs
// nothing, and a list cut short or holding an unreadable row still repairs the
// rows that arrived.
func TestAnSSLDomainListIsRepairedAsFarAsItWasRead(t *testing.T) {
	cases := []struct {
		name    string
		prepare func(script *sqlScript)
		renders int
	}{
		{"the query fails", func(script *sqlScript) {
			script.fail[sslDomainListQuery] = errors.New(lostConnectionTo)
		}, 0},
		{"the list is cut short", func(script *sqlScript) {
			script.endWith = map[string]error{sslDomainListQuery: errors.New(lostConnectionTo)}
		}, 1},
		{"a row cannot be read", func(script *sqlScript) {
			script.rows[sslDomainListQuery] = append([][]driver.Value{sslRow(nil, "bad.example", "c_bad", "", "")},
				script.rows[sslDomainListQuery]...)
		}, 1},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			f := withSSLHeal(t)
			cert, key := writeSANCertificate(t, "example.com")
			sslVhost(t, "c_example_com", vhostWithout443)
			script := sslScript([][]driver.Value{sslRow(int64(1), "example.com", "c_example_com", cert, key)})
			tc.prepare(script)
			withScript(t, script)

			HealSSLVhost443OnStartup()

			if len(f.capture.opts) != tc.renders {
				t.Errorf("renders = %d, want %d", len(f.capture.opts), tc.renders)
			}
		})
	}
}

func TestAnEmptySSLDomainListRepairsNothing(t *testing.T) {
	f := withSSLHeal(t)
	withScript(t, sslScript([][]driver.Value{}))

	HealSSLVhost443OnStartup()

	if len(f.capture.opts) != 0 || len(f.commands.argvs()) != 0 {
		t.Errorf("an empty list repaired something: renders %d, commands %q", len(f.capture.opts), f.commands.argvs())
	}
}

// A certificate the heal found but cannot install is a failure for that domain:
// nothing is generated in its place, recorded or rendered.
func TestAFoundCertificateThatCannotBeInstalledIsNotRendered(t *testing.T) {
	f := withSSLHeal(t)
	acmeDir := filepath.Join(os.Getenv("SERVIKA_ACME_HOME"), "example.com")
	writeCertificateFixture(t, filepath.Join(acmeDir, "fullchain.cer"), filepath.Join(acmeDir, "example.com.key"), "example.com", false)
	certificateSourceOwner = os.Getuid() + 1
	sslVhost(t, "c_example_com", vhostWith443)
	script := sslScript([][]driver.Value{sslRow(int64(1), "example.com", "c_example_com", "/gone.crt", "/gone.key")})
	withScript(t, script)

	HealSSLVhost443OnStartup()

	if len(f.capture.opts) != 0 || f.commands.ran("openssl") || len(repoints(script)) != 0 {
		t.Errorf("an uninstallable certificate was worked around: renders %d, commands %q, repoints %v",
			len(f.capture.opts), f.commands.argvs(), repoints(script))
	}
}

func TestNoDatabaseRepairsNoSSLVhost(t *testing.T) {
	f := withSSLHeal(t)
	withoutDatabase(t)

	HealSSLVhost443OnStartup()

	if len(f.capture.opts) != 0 {
		t.Errorf("renders = %d without a database", len(f.capture.opts))
	}
}
