package serverip

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"sort"
	"strings"
)

// The persistence unit. "ip addr add" is a runtime change and the kernel
// forgets it at the next boot, so an address added through this screen would
// quietly disappear the first time the server restarted, which is exactly when
// nobody is watching for it.
const (
	unitPath   = "/etc/systemd/system/servika-server-ips.service"
	scriptPath = "/usr/local/sbin/servika-server-ips"
	unitName   = "servika-server-ips.service"
)

// unitBody is FIXED. Nothing a request carries reaches it; the addresses live
// in the script, which is regenerated from the table.
//
// It runs after the network is up and before nginx, so a vhost bound to one of
// these addresses finds it there. RemainAfterExit keeps the unit "active" once
// the addresses are on, which is what makes "systemctl status" readable rather
// than permanently showing a dead oneshot.
const unitBody = `[Unit]
Description=Servika additional server addresses
After=network-online.target
Wants=network-online.target
Before=nginx.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=` + scriptPath + `

[Install]
WantedBy=multi-user.target
`

// scriptHeader opens the generated script.
//
// "ip addr add" answers "RTNETLINK answers: File exists" when the address is
// already there, which is the normal state on any re-run, so each line tolerates
// it rather than failing the unit. The script does NOT use "set -e" for the same
// reason: one address that cannot be added must not stop the rest, since the
// addresses are independent and a half-applied set is better than none.
const scriptHeader = `#!/usr/bin/env bash
# Generated by Servika. Regenerated whenever an address is added or removed
# through the panel; edits here are lost on the next change.
set -uo pipefail
`

// WritePersistence regenerates the boot-time script from the table and makes
// sure the unit is installed and enabled.
//
// It is called AFTER the live change succeeded, never before. The other order
// leaves a server that puts an address back on the next boot which it does not
// have now, so the screen, the running host and the next reboot would each say
// something different.
func WritePersistence(ctx context.Context, db *sql.DB) error {
	rows, err := db.QueryContext(ctx,
		`SELECT ip, interface, prefix_length, label FROM server_ips ORDER BY id`)
	if err != nil {
		return err
	}
	defer func() { _ = rows.Close() }()

	var lines []string
	for rows.Next() {
		var ip, device, label string
		var prefix int
		if err := rows.Scan(&ip, &device, &prefix, &label); err != nil {
			return err
		}
		// Every value here was validated on the way in, and it is checked again
		// on the way out: this text becomes a root shell script, and a row is
		// exactly the kind of thing that outlives the code that wrote it.
		if _, err := ValidateNew(ip, prefix); err != nil {
			return fmt.Errorf("row for %q: %w", ip, err)
		}
		if !ValidInterface(device) {
			return fmt.Errorf("row for %q names the interface %q", ip, device)
		}
		if !strings.HasPrefix(label, labelPrefix) || len(label) > maxLabelLength || !validLabel(label) {
			return fmt.Errorf("row for %q carries the label %q", ip, label)
		}
		lines = append(lines, fmt.Sprintf(
			"ip addr add %s/%d dev %s label %s 2>/dev/null || true", ip, prefix, device, label))
	}
	if err := rows.Err(); err != nil {
		return err
	}
	sort.Strings(lines)

	body := scriptHeader + strings.Join(lines, "\n") + "\n"
	// #nosec G306 -- a root-owned boot script systemd must execute; it carries
	// no secret, every line is built from validated values.
	if err := os.WriteFile(scriptPath, []byte(body), 0o700); err != nil {
		return err
	}
	// #nosec G306 -- a systemd unit file the manager must read.
	if err := os.WriteFile(unitPath, []byte(unitBody), 0o644); err != nil {
		return err
	}
	if out, err := run(ctx, "systemctl", "daemon-reload"); err != nil {
		return fmt.Errorf("daemon-reload: %s", strings.TrimSpace(out))
	}
	if out, err := run(ctx, "systemctl", "enable", unitName); err != nil {
		return fmt.Errorf("enable %s: %s", unitName, strings.TrimSpace(out))
	}
	return nil
}

// validLabel accepts only what this package generates, so nothing a row carries
// can turn a label into another shell word.
func validLabel(label string) bool {
	for _, r := range label {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-':
		default:
			return false
		}
	}
	return true
}
